services:
  web-app:
    build:
      context: .
    container_name: web-app-container
    restart: always
    links:
      - "database:database"
    ports:
      - "8000:8000"
    volumes:
      - ./service:/service
    environment:
      - DB_HOST=database
      - DB_USER=dbuser
      - DB_NAME=dbname
      - DB_PASS=pass
    networks:
      - web-app-net

    command: "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database

  database:
    image: postgres:17-alpine
    container_name: postgres-container
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
    volumes:
      - service_postgres:/var/lib/postgresql/data
    networks:
      - web-app-net


networks:
  web-app-net:
    driver: bridge

volumes:
  service_postgres:
