services:
  web-app:
    build:
      context: .
    image: web-app
    container_name: web-app-container
    restart: always
    links:
      - "database:database"
    ports:
      - "8000:8000"
    volumes:
      - ./service:/service
    environment:
      - DB_HOST=database
      - DB_USER=dbuser
      - DB_NAME=dbname
      - DB_PASS=pass
    networks:
      - web-app-net

    command: "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database

  database:
    image: postgres:17-alpine
    container_name: postgres-container
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
    volumes:
      - service_postgres:/var/lib/postgresql/data
    networks:
      - web-app-net

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - '8080:8080'
    depends_on:
      - database
    networks:
      - web-app-net


  redis:
    image: redis:7.4-alpine
    container_name: redis-container
    hostname: redis
    networks:
      - web-app-net
    volumes:
      - service_redis:/data

  worker:
    image: web-app:latest
    container_name: worker_container
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    networks:
      - web-app-net
    volumes:
      - ./service:/service
    links:
      - redis
    environment:
      - DB_HOST=database
      - DB_USER=dbuser
      - DB_NAME=dbname
      - DB_PASS=pass
    depends_on:
      - redis
      - web-app
      - database

  worker2:
    image: web-app:latest
    container_name: worker_container2
    hostname: worker2
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    networks:
      - web-app-net
    volumes:
      - ./service:/service
    links:
      - redis
    environment:
      - DB_HOST=database
      - DB_USER=dbuser
      - DB_NAME=dbname
      - DB_PASS=pass
    depends_on:
      - redis
      - web-app
      - database

  flower:
    image: web-app:latest
    container_name: flower_container
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./service:/service
    networks:
      - web-app-net
    links:
      - redis
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - web-app


networks:
  web-app-net:
    driver: bridge

volumes:
  service_postgres:
  service_redis:
